# Generated by Django 5.0.4 on 2024-06-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
