# Generated by Django 5.0.4 on 2024-06-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pictures/default.jpg', upload_to='media/profile_pictures/'),
        ),
    ]
