# Generated by Django 5.0.4 on 2024-06-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
