# Generated by Django 5.0.4 on 2024-06-25 03:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', storage=storages.backends.s3.S3Storage(), upload_to='profile_pics'),
        ),
    ]
