# Generated by Django 5.0.4 on 2024-06-27 03:25

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to=api.models.team_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_actual', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finals', models.ManyToManyField(blank=True, related_name='finals', to='api.team')),
                ('left_side_quarter_finals', models.ManyToManyField(blank=True, related_name='left_quarter_finals', to='api.team')),
                ('left_side_round_of_16_teams', models.ManyToManyField(blank=True, related_name='left_round_of_16', to='api.team')),
                ('left_side_semi_finals', models.ManyToManyField(blank=True, related_name='left_semi_finals', to='api.team')),
                ('right_side_quarter_finals', models.ManyToManyField(blank=True, related_name='right_quarter_finals', to='api.team')),
                ('right_side_round_of_16_teams', models.ManyToManyField(blank=True, related_name='right_round_of_16', to='api.team')),
                ('right_side_semi_finals', models.ManyToManyField(blank=True, related_name='right_semi_finals', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to=api.models.tournament_upload_path)),
                ('logo', models.ImageField(upload_to=api.models.tournament_upload_path)),
                ('point_system', models.JSONField(default=list)),
                ('correct_score_bonus', models.IntegerField(default=0)),
                ('winner_reward', models.TextField()),
                ('loser_forfeit', models.TextField()),
                ('actual_bracket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_bracket', to='api.bracket')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('predicted_brackets', models.ManyToManyField(blank=True, related_name='predicted_brackets', to='api.bracket')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.tournament'),
        ),
    ]
