# Generated by Django 5.0.4 on 2024-06-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_team_bracket_tournament_team_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='api.team'),
        ),
    ]
