# Generated by Django 5.0.4 on 2024-06-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_bracket_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
