# Generated by Django 5.0.4 on 2024-06-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_bracket_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='finals',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='left_side_quarter_finals',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='left_side_round_of_16_teams',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='left_side_semi_finals',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='right_side_quarter_finals',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='right_side_round_of_16_teams',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='right_side_semi_finals',
        ),
        migrations.AddField(
            model_name='bracket',
            name='finals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bracket',
            name='left_side_quarter_finals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bracket',
            name='left_side_round_of_16_teams',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bracket',
            name='left_side_semi_finals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bracket',
            name='right_side_quarter_finals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bracket',
            name='right_side_round_of_16_teams',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bracket',
            name='right_side_semi_finals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
