# Generated by Django 5.0.4 on 2024-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_bracket_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='team_size',
            field=models.IntegerField(default=16),
        ),
    ]
