# Generated by Django 5.0.4 on 2024-06-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_tournament_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='imdb_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
