# Generated by Django 5.0.4 on 2024-07-03 20:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.note_image_upload_path),
        ),
        migrations.AddField(
            model_name='note',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.note_image_upload_path),
        ),
        migrations.AddField(
            model_name='note',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.note_image_upload_path),
        ),
    ]
