# Generated by Django 5.0.4 on 2024-07-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_note_image1_note_image2_note_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, related_name='follow_requests_received', to='api.profile'),
        ),
    ]
