# Generated by Django 5.0.4 on 2024-07-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_profile_follow_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, related_name='follow_requests_received', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='api.profile'),
        ),
    ]
