# Generated by Django 5.0.4 on 2024-07-09 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_profile_follow_requests_profile_followers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_by',
            field=models.ManyToManyField(default=0, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocking',
            field=models.ManyToManyField(default=0, related_name='blocking', to=settings.AUTH_USER_MODEL),
        ),
    ]
