# Generated by Django 5.0.4 on 2024-07-13 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_profile_blocked_by_profile_blocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_challenger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_subber',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenger_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenger_note', to='api.note')),
                ('original_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='api.note')),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='api.note')),
                ('sub_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_note', to='api.note')),
            ],
        ),
    ]
