# Generated by Django 5.0.4 on 2024-07-17 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_note_is_challenger_note_is_subber_challenge_sub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenger_picks',
            field=models.ManyToManyField(default=0, related_name='challenger_picks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='original_picks',
            field=models.ManyToManyField(default=0, related_name='original_picks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='wager',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='original_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='api.note'),
        ),
    ]
