# Generated by Django 5.0.4 on 2024-08-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_challenge_accepted_challenge_challenger_picks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_challenges_made',
            field=models.ManyToManyField(blank=True, related_name='active_challenges_made', to='api.challenge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='active_challenges_received',
            field=models.ManyToManyField(blank=True, related_name='active_challenges_received', to='api.challenge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_accept_challenges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='challenge_requests',
            field=models.ManyToManyField(blank=True, related_name='challenge_requests', to='api.challenge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='challenges_declined',
            field=models.ManyToManyField(blank=True, related_name='challenges_declined', to='api.challenge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='challenges_sent',
            field=models.ManyToManyField(blank=True, related_name='challenges_sent', to='api.challenge'),
        ),
    ]
